### ISSUE TITLE
OS

### ISSUE THREAD

**Issue by Creator** [ccTCP/ccTCPf#1]
The OS should only be used by:
- the router
- the switch

It should not be used by:
- the end user

**Comment by cmdstack** [comment]
Yes, we will still make our own os for the end user so that people can get our product on all devices that they need. The API while its purpose is for other programs, we will still make our own os to encap that API for each device

**Comment by cmdstack** [comment]
remember, this has people looking to train in mind as well

**Comment by Creator** [comment]
But writing an OS would include much more than just TCP. It necessitates a coroutine manages, some apps, proper APIs and a lot of stuff that has nothing to do with TCP. I mean, you don't get a special OS in order to be able to use TCP. TCP is implemented in OSes and I think that our main goal is to create a working TCP protocol.

**Comment by Creator** [comment]
For the routers, there will be a CLI from where people will be able to manage them. Also I thought about adding TCP api to OSes as OmniOS or NovaOS.

**Comment by cmdstack** [comment]
They will be networking oses, have a look at cisco devices, they aren't full blown fancy oses they are minimalistic systems design specifically to run the stack and associated protocols, we are doing the same

**Comment by cmdstack** [comment]
also, I do hope that you implement tcp into OmniOS/NovaOS
