### ISSUE TITLE
Mobile internet

### ISSUE THREAD

**Issue by Creator** [ccTCP/ccTCPf#2]
Maybe we should add a mobile internet like protocol:
**Pros:**
- turtles
- PDA's

**Comment by cmdstack** [comment]
I don't understand. explain

**Comment by Creator** [comment]
Like 3G

**Comment by cmdstack** [comment]
? I still don't understand as this is just a wireless implementation which we will already include. What is the purpose and how would it work (your 'mobile internet')

**Comment by jaredallard** [comment]
3G is essentially just radio broadcast'd signals, there is no "special" aspect to it that I know of.

**Comment by jaredallard** [comment]
in the end we'd treat them the same

**Comment by cmdstack** [comment]
exactly what I was saying, it is literally a wireless implementation so what is the purpose of another protocol?

**Comment by jaredallard** [comment]
![](https://imgs.xkcd.com/comics/standards.png)
