### ISSUE TITLE
Connection Topology

### ISSUE THREAD

**Issue by Creator** [ccTCP/ccTCPf#3]
I was thinking about how we should connect the machines to the switches, and I figured out two ways:
**\- one physical cable per device with fixed channel:**
- Pros:
  Real life like tree topology
- Cons:
  Allows a maximum of 6 devices
  **\- one physical channel for all devices and different channels**
- Pros:
  Allows a very large number of devices
  Does not take a lot of space
- Cons:
  Less secure

I will ask you to write you opinion in the comments, so we can figure this out and start coding

:smile:

**Comment by InDieTasten** [comment]
I don't see the need for this many devices, and it also conflicts with a lot of other stuff.
If you imagine the channels in a cable as many cables, every cable would have 65k clones of itself as channels, from which you can read 128 at a time with one modem.

Therefor, every modem you place at a computer will act as if it was out of 128 NICs, which is uncommon IMO. Much more common is to have 1 to 6 NIC's on a device, which would refer to only one channel.

Another thing is, that you would need to agree with the opponent modems of the cable on the channels you use. It makes everything much more complicated and ruins the simplicity and "purity" of our connections, making it much more difficult to understand it.

And we already agreed on this fact, so I will feel free to close this. If there are any complains, you can reopen it
