### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by TYKUHN2** [ccTCP/ccTCPf#4]
mount.lua:453: Expected function got nil!
After ethernet, Probably Interface.

**Comment by Creator** [comment]
Yeah, it is kinda not ready.

**Comment by TYKUHN2** [comment]
Well now that is one less thing to track down.

**Comment by cmdstack** [comment]
This project has been inactive for a while and now I'm ready to pick it back up, I'll be submitting alot over the next week :)

**Comment by Creator** [comment]
I'm in too. Just tell me what to do.
