### ISSUE TITLE
Formatting specifications

### ISSUE THREAD

**Issue by Creator** [ccTCP/ccTCPf#5]
Releases:
- shall be stored, not in a release directory, but in the special GitHub/Git release.
- should have version numbers and stable not stable.

Code: 
- shall be in the src directory
- the main directory will have code for compilation, which will be attached to releases as "binaries"

Any suggestions?

**Comment by cmdstack** [comment]
seems overly complex when all we need is basic separation which is what it has now. We can develop the src and then roll a compiled copy to release/beta[or]stable with the version # that was pushed.

**Comment by jaredallard** [comment]
I :+1: this issue

**Comment by cmdstack** [comment]
Thanks, so then yes do the complex route?

**Comment by Creator** [comment]
Apparently.

**Comment by BitForger** [comment]
:+1:
